services:
  scms:
    image: ghcr.io/evilgeniusgames/scms:latest
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AdminEmail=${AdminEmail}
      - AdminPassword=${AdminPassword}
      - AdminUsername=${AdminUsername}
    volumes:
      - ./SiteData/Database:/app/data
      - ./SiteData/uploads:/app/wwwroot/uploads
    restart: unless-stopped
